// Code generated by MockGen. DO NOT EDIT.
// Source: saml.dev/gome-assistant (interfaces: State)
//
// Generated by this command:
//
//	mockgen -destination=mock_state.go -package=mocks saml.dev/gome-assistant State
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gomeassistant "saml.dev/gome-assistant"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// AfterSunrise mocks base method.
func (m *MockState) AfterSunrise(arg0 ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AfterSunrise", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AfterSunrise indicates an expected call of AfterSunrise.
func (mr *MockStateMockRecorder) AfterSunrise(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterSunrise", reflect.TypeOf((*MockState)(nil).AfterSunrise), arg0...)
}

// AfterSunset mocks base method.
func (m *MockState) AfterSunset(arg0 ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AfterSunset", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AfterSunset indicates an expected call of AfterSunset.
func (mr *MockStateMockRecorder) AfterSunset(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterSunset", reflect.TypeOf((*MockState)(nil).AfterSunset), arg0...)
}

// BeforeSunrise mocks base method.
func (m *MockState) BeforeSunrise(arg0 ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeforeSunrise", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BeforeSunrise indicates an expected call of BeforeSunrise.
func (mr *MockStateMockRecorder) BeforeSunrise(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeSunrise", reflect.TypeOf((*MockState)(nil).BeforeSunrise), arg0...)
}

// BeforeSunset mocks base method.
func (m *MockState) BeforeSunset(arg0 ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeforeSunset", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BeforeSunset indicates an expected call of BeforeSunset.
func (mr *MockStateMockRecorder) BeforeSunset(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeSunset", reflect.TypeOf((*MockState)(nil).BeforeSunset), arg0...)
}

// Equals mocks base method.
func (m *MockState) Equals(entityId, state string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equals", entityId, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Equals indicates an expected call of Equals.
func (mr *MockStateMockRecorder) Equals(entityId, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equals", reflect.TypeOf((*MockState)(nil).Equals), entityId, state)
}

// Get mocks base method.
func (m *MockState) Get(entityId string) (gomeassistant.EntityState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", entityId)
	ret0, _ := ret[0].(gomeassistant.EntityState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateMockRecorder) Get(entityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockState)(nil).Get), entityId)
}

// ListEntities mocks base method.
func (m *MockState) ListEntities() ([]gomeassistant.EntityState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntities")
	ret0, _ := ret[0].([]gomeassistant.EntityState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntities indicates an expected call of ListEntities.
func (mr *MockStateMockRecorder) ListEntities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntities", reflect.TypeOf((*MockState)(nil).ListEntities))
}
