// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=mock_interfaces.go -package=mocks -source=interfaces.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	notifications "home-go/notifications"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	gomeassistant "saml.dev/gome-assistant"
)

// MockStateInterface is a mock of StateInterface interface.
type MockStateInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStateInterfaceMockRecorder
	isgomock struct{}
}

// MockStateInterfaceMockRecorder is the mock recorder for MockStateInterface.
type MockStateInterfaceMockRecorder struct {
	mock *MockStateInterface
}

// NewMockStateInterface creates a new mock instance.
func NewMockStateInterface(ctrl *gomock.Controller) *MockStateInterface {
	mock := &MockStateInterface{ctrl: ctrl}
	mock.recorder = &MockStateInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateInterface) EXPECT() *MockStateInterfaceMockRecorder {
	return m.recorder
}

// AfterSunrise mocks base method.
func (m *MockStateInterface) AfterSunrise(offset ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offset {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AfterSunrise", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AfterSunrise indicates an expected call of AfterSunrise.
func (mr *MockStateInterfaceMockRecorder) AfterSunrise(offset ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterSunrise", reflect.TypeOf((*MockStateInterface)(nil).AfterSunrise), offset...)
}

// AfterSunset mocks base method.
func (m *MockStateInterface) AfterSunset(offset ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offset {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AfterSunset", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AfterSunset indicates an expected call of AfterSunset.
func (mr *MockStateInterfaceMockRecorder) AfterSunset(offset ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AfterSunset", reflect.TypeOf((*MockStateInterface)(nil).AfterSunset), offset...)
}

// BeforeSunrise mocks base method.
func (m *MockStateInterface) BeforeSunrise(offset ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offset {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeforeSunrise", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BeforeSunrise indicates an expected call of BeforeSunrise.
func (mr *MockStateInterfaceMockRecorder) BeforeSunrise(offset ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeSunrise", reflect.TypeOf((*MockStateInterface)(nil).BeforeSunrise), offset...)
}

// BeforeSunset mocks base method.
func (m *MockStateInterface) BeforeSunset(offset ...gomeassistant.DurationString) bool {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range offset {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BeforeSunset", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// BeforeSunset indicates an expected call of BeforeSunset.
func (mr *MockStateInterfaceMockRecorder) BeforeSunset(offset ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeforeSunset", reflect.TypeOf((*MockStateInterface)(nil).BeforeSunset), offset...)
}

// Equals mocks base method.
func (m *MockStateInterface) Equals(entityID, state string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Equals", entityID, state)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Equals indicates an expected call of Equals.
func (mr *MockStateInterfaceMockRecorder) Equals(entityID, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Equals", reflect.TypeOf((*MockStateInterface)(nil).Equals), entityID, state)
}

// Get mocks base method.
func (m *MockStateInterface) Get(entityID string) (gomeassistant.EntityState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", entityID)
	ret0, _ := ret[0].(gomeassistant.EntityState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStateInterfaceMockRecorder) Get(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStateInterface)(nil).Get), entityID)
}

// ListEntities mocks base method.
func (m *MockStateInterface) ListEntities() ([]gomeassistant.EntityState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntities")
	ret0, _ := ret[0].([]gomeassistant.EntityState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntities indicates an expected call of ListEntities.
func (mr *MockStateInterfaceMockRecorder) ListEntities() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntities", reflect.TypeOf((*MockStateInterface)(nil).ListEntities))
}

// MockSwitchInterface is a mock of SwitchInterface interface.
type MockSwitchInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSwitchInterfaceMockRecorder
	isgomock struct{}
}

// MockSwitchInterfaceMockRecorder is the mock recorder for MockSwitchInterface.
type MockSwitchInterfaceMockRecorder struct {
	mock *MockSwitchInterface
}

// NewMockSwitchInterface creates a new mock instance.
func NewMockSwitchInterface(ctrl *gomock.Controller) *MockSwitchInterface {
	mock := &MockSwitchInterface{ctrl: ctrl}
	mock.recorder = &MockSwitchInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSwitchInterface) EXPECT() *MockSwitchInterfaceMockRecorder {
	return m.recorder
}

// TurnOff mocks base method.
func (m *MockSwitchInterface) TurnOff(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnOff", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOff indicates an expected call of TurnOff.
func (mr *MockSwitchInterfaceMockRecorder) TurnOff(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOff", reflect.TypeOf((*MockSwitchInterface)(nil).TurnOff), entityID)
}

// TurnOn mocks base method.
func (m *MockSwitchInterface) TurnOn(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnOn", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOn indicates an expected call of TurnOn.
func (mr *MockSwitchInterfaceMockRecorder) TurnOn(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOn", reflect.TypeOf((*MockSwitchInterface)(nil).TurnOn), entityID)
}

// MockInputBooleanInterface is a mock of InputBooleanInterface interface.
type MockInputBooleanInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInputBooleanInterfaceMockRecorder
	isgomock struct{}
}

// MockInputBooleanInterfaceMockRecorder is the mock recorder for MockInputBooleanInterface.
type MockInputBooleanInterfaceMockRecorder struct {
	mock *MockInputBooleanInterface
}

// NewMockInputBooleanInterface creates a new mock instance.
func NewMockInputBooleanInterface(ctrl *gomock.Controller) *MockInputBooleanInterface {
	mock := &MockInputBooleanInterface{ctrl: ctrl}
	mock.recorder = &MockInputBooleanInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputBooleanInterface) EXPECT() *MockInputBooleanInterfaceMockRecorder {
	return m.recorder
}

// Toggle mocks base method.
func (m *MockInputBooleanInterface) Toggle(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Toggle", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Toggle indicates an expected call of Toggle.
func (mr *MockInputBooleanInterfaceMockRecorder) Toggle(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockInputBooleanInterface)(nil).Toggle), entityID)
}

// TurnOff mocks base method.
func (m *MockInputBooleanInterface) TurnOff(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnOff", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOff indicates an expected call of TurnOff.
func (mr *MockInputBooleanInterfaceMockRecorder) TurnOff(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOff", reflect.TypeOf((*MockInputBooleanInterface)(nil).TurnOff), entityID)
}

// TurnOn mocks base method.
func (m *MockInputBooleanInterface) TurnOn(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnOn", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOn indicates an expected call of TurnOn.
func (mr *MockInputBooleanInterfaceMockRecorder) TurnOn(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOn", reflect.TypeOf((*MockInputBooleanInterface)(nil).TurnOn), entityID)
}

// MockInputNumberInterface is a mock of InputNumberInterface interface.
type MockInputNumberInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInputNumberInterfaceMockRecorder
	isgomock struct{}
}

// MockInputNumberInterfaceMockRecorder is the mock recorder for MockInputNumberInterface.
type MockInputNumberInterfaceMockRecorder struct {
	mock *MockInputNumberInterface
}

// NewMockInputNumberInterface creates a new mock instance.
func NewMockInputNumberInterface(ctrl *gomock.Controller) *MockInputNumberInterface {
	mock := &MockInputNumberInterface{ctrl: ctrl}
	mock.recorder = &MockInputNumberInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputNumberInterface) EXPECT() *MockInputNumberInterfaceMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockInputNumberInterface) Set(entityID string, value float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", entityID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInputNumberInterfaceMockRecorder) Set(entityID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInputNumberInterface)(nil).Set), entityID, value)
}

// MockInputTextInterface is a mock of InputTextInterface interface.
type MockInputTextInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInputTextInterfaceMockRecorder
	isgomock struct{}
}

// MockInputTextInterfaceMockRecorder is the mock recorder for MockInputTextInterface.
type MockInputTextInterfaceMockRecorder struct {
	mock *MockInputTextInterface
}

// NewMockInputTextInterface creates a new mock instance.
func NewMockInputTextInterface(ctrl *gomock.Controller) *MockInputTextInterface {
	mock := &MockInputTextInterface{ctrl: ctrl}
	mock.recorder = &MockInputTextInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputTextInterface) EXPECT() *MockInputTextInterfaceMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockInputTextInterface) Set(entityID, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", entityID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInputTextInterfaceMockRecorder) Set(entityID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInputTextInterface)(nil).Set), entityID, value)
}

// MockInputDatetimeInterface is a mock of InputDatetimeInterface interface.
type MockInputDatetimeInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInputDatetimeInterfaceMockRecorder
	isgomock struct{}
}

// MockInputDatetimeInterfaceMockRecorder is the mock recorder for MockInputDatetimeInterface.
type MockInputDatetimeInterfaceMockRecorder struct {
	mock *MockInputDatetimeInterface
}

// NewMockInputDatetimeInterface creates a new mock instance.
func NewMockInputDatetimeInterface(ctrl *gomock.Controller) *MockInputDatetimeInterface {
	mock := &MockInputDatetimeInterface{ctrl: ctrl}
	mock.recorder = &MockInputDatetimeInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputDatetimeInterface) EXPECT() *MockInputDatetimeInterfaceMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockInputDatetimeInterface) Set(entityID string, value time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", entityID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockInputDatetimeInterfaceMockRecorder) Set(entityID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockInputDatetimeInterface)(nil).Set), entityID, value)
}

// MockHomeAssistantInterface is a mock of HomeAssistantInterface interface.
type MockHomeAssistantInterface struct {
	ctrl     *gomock.Controller
	recorder *MockHomeAssistantInterfaceMockRecorder
	isgomock struct{}
}

// MockHomeAssistantInterfaceMockRecorder is the mock recorder for MockHomeAssistantInterface.
type MockHomeAssistantInterfaceMockRecorder struct {
	mock *MockHomeAssistantInterface
}

// NewMockHomeAssistantInterface creates a new mock instance.
func NewMockHomeAssistantInterface(ctrl *gomock.Controller) *MockHomeAssistantInterface {
	mock := &MockHomeAssistantInterface{ctrl: ctrl}
	mock.recorder = &MockHomeAssistantInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHomeAssistantInterface) EXPECT() *MockHomeAssistantInterfaceMockRecorder {
	return m.recorder
}

// Toggle mocks base method.
func (m *MockHomeAssistantInterface) Toggle(entityID string, serviceData ...map[string]any) error {
	m.ctrl.T.Helper()
	varargs := []any{entityID}
	for _, a := range serviceData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Toggle", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Toggle indicates an expected call of Toggle.
func (mr *MockHomeAssistantInterfaceMockRecorder) Toggle(entityID any, serviceData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{entityID}, serviceData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockHomeAssistantInterface)(nil).Toggle), varargs...)
}

// TurnOff mocks base method.
func (m *MockHomeAssistantInterface) TurnOff(entityID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TurnOff", entityID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOff indicates an expected call of TurnOff.
func (mr *MockHomeAssistantInterfaceMockRecorder) TurnOff(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOff", reflect.TypeOf((*MockHomeAssistantInterface)(nil).TurnOff), entityID)
}

// TurnOn mocks base method.
func (m *MockHomeAssistantInterface) TurnOn(entityID string, serviceData ...map[string]any) error {
	m.ctrl.T.Helper()
	varargs := []any{entityID}
	for _, a := range serviceData {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TurnOn", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// TurnOn indicates an expected call of TurnOn.
func (mr *MockHomeAssistantInterfaceMockRecorder) TurnOn(entityID any, serviceData ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{entityID}, serviceData...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TurnOn", reflect.TypeOf((*MockHomeAssistantInterface)(nil).TurnOn), varargs...)
}

// MockPricingServiceInterface is a mock of PricingServiceInterface interface.
type MockPricingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPricingServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPricingServiceInterfaceMockRecorder is the mock recorder for MockPricingServiceInterface.
type MockPricingServiceInterfaceMockRecorder struct {
	mock *MockPricingServiceInterface
}

// NewMockPricingServiceInterface creates a new mock instance.
func NewMockPricingServiceInterface(ctrl *gomock.Controller) *MockPricingServiceInterface {
	mock := &MockPricingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPricingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingServiceInterface) EXPECT() *MockPricingServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAveragePrice mocks base method.
func (m *MockPricingServiceInterface) GetAveragePrice() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAveragePrice")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAveragePrice indicates an expected call of GetAveragePrice.
func (mr *MockPricingServiceInterfaceMockRecorder) GetAveragePrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAveragePrice", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetAveragePrice))
}

// GetCurrentPrice mocks base method.
func (m *MockPricingServiceInterface) GetCurrentPrice() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockPricingServiceInterfaceMockRecorder) GetCurrentPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetCurrentPrice))
}

// GetPriceSlots mocks base method.
func (m *MockPricingServiceInterface) GetPriceSlots() ([]PriceSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceSlots")
	ret0, _ := ret[0].([]PriceSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceSlots indicates an expected call of GetPriceSlots.
func (mr *MockPricingServiceInterfaceMockRecorder) GetPriceSlots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceSlots", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetPriceSlots))
}

// GetPriceSlotsInWindow mocks base method.
func (m *MockPricingServiceInterface) GetPriceSlotsInWindow(from, until time.Time) ([]PriceSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceSlotsInWindow", from, until)
	ret0, _ := ret[0].([]PriceSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceSlotsInWindow indicates an expected call of GetPriceSlotsInWindow.
func (mr *MockPricingServiceInterfaceMockRecorder) GetPriceSlotsInWindow(from, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceSlotsInWindow", reflect.TypeOf((*MockPricingServiceInterface)(nil).GetPriceSlotsInWindow), from, until)
}

// IsCurrentlyExpensive mocks base method.
func (m *MockPricingServiceInterface) IsCurrentlyExpensive() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrentlyExpensive")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCurrentlyExpensive indicates an expected call of IsCurrentlyExpensive.
func (mr *MockPricingServiceInterfaceMockRecorder) IsCurrentlyExpensive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrentlyExpensive", reflect.TypeOf((*MockPricingServiceInterface)(nil).IsCurrentlyExpensive))
}

// MockNotificationSenderInterface is a mock of NotificationSenderInterface interface.
type MockNotificationSenderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationSenderInterfaceMockRecorder
	isgomock struct{}
}

// MockNotificationSenderInterfaceMockRecorder is the mock recorder for MockNotificationSenderInterface.
type MockNotificationSenderInterfaceMockRecorder struct {
	mock *MockNotificationSenderInterface
}

// NewMockNotificationSenderInterface creates a new mock instance.
func NewMockNotificationSenderInterface(ctrl *gomock.Controller) *MockNotificationSenderInterface {
	mock := &MockNotificationSenderInterface{ctrl: ctrl}
	mock.recorder = &MockNotificationSenderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationSenderInterface) EXPECT() *MockNotificationSenderInterfaceMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockNotificationSenderInterface) Notify(event notifications.NotificationEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockNotificationSenderInterfaceMockRecorder) Notify(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockNotificationSenderInterface)(nil).Notify), event)
}
