// Code generated by MockGen. DO NOT EDIT.
// Source: home-go/internal/domain/devices/dishwasher (interfaces: ScheduleStateStore)
//
// Generated by this command:
//
//	mockgen -destination=../../../../mocks/domain/devices/dishwasher/scheduled_state_store.go -package=dishwasher home-go/internal/domain/devices/dishwasher ScheduleStateStore
//

// Package dishwasher is a generated GoMock package.
package dishwasher

import (
	dishwasher "home-go/internal/domain/devices/dishwasher"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockScheduleStateStore is a mock of ScheduleStateStore interface.
type MockScheduleStateStore struct {
	ctrl     *gomock.Controller
	recorder *MockScheduleStateStoreMockRecorder
	isgomock struct{}
}

// MockScheduleStateStoreMockRecorder is the mock recorder for MockScheduleStateStore.
type MockScheduleStateStoreMockRecorder struct {
	mock *MockScheduleStateStore
}

// NewMockScheduleStateStore creates a new mock instance.
func NewMockScheduleStateStore(ctrl *gomock.Controller) *MockScheduleStateStore {
	mock := &MockScheduleStateStore{ctrl: ctrl}
	mock.recorder = &MockScheduleStateStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduleStateStore) EXPECT() *MockScheduleStateStoreMockRecorder {
	return m.recorder
}

// ClearSchedule mocks base method.
func (m *MockScheduleStateStore) ClearSchedule() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSchedule")
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSchedule indicates an expected call of ClearSchedule.
func (mr *MockScheduleStateStoreMockRecorder) ClearSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSchedule", reflect.TypeOf((*MockScheduleStateStore)(nil).ClearSchedule))
}

// IsScheduleCancelled mocks base method.
func (m *MockScheduleStateStore) IsScheduleCancelled() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsScheduleCancelled")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsScheduleCancelled indicates an expected call of IsScheduleCancelled.
func (mr *MockScheduleStateStoreMockRecorder) IsScheduleCancelled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsScheduleCancelled", reflect.TypeOf((*MockScheduleStateStore)(nil).IsScheduleCancelled))
}

// RestoreSchedule mocks base method.
func (m *MockScheduleStateStore) RestoreSchedule() (*dishwasher.PendingSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreSchedule")
	ret0, _ := ret[0].(*dishwasher.PendingSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreSchedule indicates an expected call of RestoreSchedule.
func (mr *MockScheduleStateStoreMockRecorder) RestoreSchedule() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreSchedule", reflect.TypeOf((*MockScheduleStateStore)(nil).RestoreSchedule))
}

// SaveSchedule mocks base method.
func (m *MockScheduleStateStore) SaveSchedule(arg0 *dishwasher.PendingSchedule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSchedule", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSchedule indicates an expected call of SaveSchedule.
func (mr *MockScheduleStateStoreMockRecorder) SaveSchedule(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSchedule", reflect.TypeOf((*MockScheduleStateStore)(nil).SaveSchedule), arg0)
}
