// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
)

type Reminder struct {
	ID                string        `json:"id"`
	ScheduleKind      string        `json:"schedule_kind"`
	TriggerAt         int64         `json:"trigger_at"`
	NextRunAt         sql.NullInt64 `json:"next_run_at"`
	RecurEverySeconds sql.NullInt64 `json:"recur_every_seconds"`
	ValidUntil        sql.NullInt64 `json:"valid_until"`
	RequiresAck       bool          `json:"requires_ack"`
	FireCount         int32         `json:"fire_count"`
	Profile           string        `json:"profile"`
	LastFiredAt       sql.NullInt64 `json:"last_fired_at"`
	Source            string        `json:"source"`
	Owner             string        `json:"owner"`
	Message           string        `json:"message"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
}

type ReminderAck struct {
	ReminderID string `json:"reminder_id"`
	UserID     string `json:"user_id"`
	AckedAt    int64  `json:"acked_at"`
}

type ReminderTarget struct {
	ReminderID string `json:"reminder_id"`
	UserID     string `json:"user_id"`
}
