// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
)

type Querier interface {
	DeleteAcks(ctx context.Context, reminderID string) error
	DeleteTargets(ctx context.Context, reminderID string) error
	GetReminder(ctx context.Context, id string) (Reminder, error)
	ListAcks(ctx context.Context, reminderID string) ([]ListAcksRow, error)
	ListActiveReminders(ctx context.Context) ([]Reminder, error)
	ListRemindersDueBefore(ctx context.Context, arg ListRemindersDueBeforeParams) ([]Reminder, error)
	ListTargets(ctx context.Context, reminderID string) ([]string, error)
	UpsertAck(ctx context.Context, arg UpsertAckParams) error
	UpsertReminder(ctx context.Context, arg UpsertReminderParams) error
	UpsertTarget(ctx context.Context, arg UpsertTargetParams) error
}

var _ Querier = (*Queries)(nil)
