// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: reminders.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAcks = `-- name: DeleteAcks :exec
DELETE FROM reminder_acks WHERE reminder_id = $1
`

func (q *Queries) DeleteAcks(ctx context.Context, reminderID string) error {
	_, err := q.db.ExecContext(ctx, deleteAcks, reminderID)
	return err
}

const deleteTargets = `-- name: DeleteTargets :exec
DELETE FROM reminder_targets WHERE reminder_id = $1
`

func (q *Queries) DeleteTargets(ctx context.Context, reminderID string) error {
	_, err := q.db.ExecContext(ctx, deleteTargets, reminderID)
	return err
}

const getReminder = `-- name: GetReminder :one
SELECT id, schedule_kind, trigger_at, next_run_at, recur_every_seconds, valid_until, requires_ack, completion_policy, profile, status, last_fired_at, source, owner, message, created_at, updated_at FROM reminders WHERE id = $1
`

func (q *Queries) GetReminder(ctx context.Context, id string) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, getReminder, id)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.ScheduleKind,
		&i.TriggerAt,
		&i.NextRunAt,
		&i.RecurEverySeconds,
		&i.ValidUntil,
		&i.RequiresAck,
		&i.CompletionPolicy,
		&i.Profile,
		&i.Status,
		&i.LastFiredAt,
		&i.Source,
		&i.Owner,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAcks = `-- name: ListAcks :many
SELECT user_id, acked_at FROM reminder_acks WHERE reminder_id = $1 ORDER BY user_id
`

type ListAcksRow struct {
	UserID  string `json:"user_id"`
	AckedAt int64  `json:"acked_at"`
}

func (q *Queries) ListAcks(ctx context.Context, reminderID string) ([]ListAcksRow, error) {
	rows, err := q.db.QueryContext(ctx, listAcks, reminderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAcksRow
	for rows.Next() {
		var i ListAcksRow
		if err := rows.Scan(&i.UserID, &i.AckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveReminders = `-- name: ListActiveReminders :many
SELECT id, schedule_kind, trigger_at, next_run_at, recur_every_seconds, valid_until, requires_ack, completion_policy, profile, status, last_fired_at, source, owner, message, created_at, updated_at FROM reminders WHERE status = 'active'
`

func (q *Queries) ListActiveReminders(ctx context.Context) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listActiveReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleKind,
			&i.TriggerAt,
			&i.NextRunAt,
			&i.RecurEverySeconds,
			&i.ValidUntil,
			&i.RequiresAck,
			&i.CompletionPolicy,
			&i.Profile,
			&i.Status,
			&i.LastFiredAt,
			&i.Source,
			&i.Owner,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemindersDueBefore = `-- name: ListRemindersDueBefore :many
SELECT id, schedule_kind, trigger_at, next_run_at, recur_every_seconds, valid_until, requires_ack, completion_policy, profile, status, last_fired_at, source, owner, message, created_at, updated_at FROM reminders
WHERE status = 'active'
  AND (
    (next_run_at IS NOT NULL AND next_run_at <= $1)
    OR (next_run_at IS NULL AND trigger_at <= $2)
  )
`

type ListRemindersDueBeforeParams struct {
	NextRunAt sql.NullInt64 `json:"next_run_at"`
	TriggerAt int64         `json:"trigger_at"`
}

func (q *Queries) ListRemindersDueBefore(ctx context.Context, arg ListRemindersDueBeforeParams) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, listRemindersDueBefore, arg.NextRunAt, arg.TriggerAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.ScheduleKind,
			&i.TriggerAt,
			&i.NextRunAt,
			&i.RecurEverySeconds,
			&i.ValidUntil,
			&i.RequiresAck,
			&i.CompletionPolicy,
			&i.Profile,
			&i.Status,
			&i.LastFiredAt,
			&i.Source,
			&i.Owner,
			&i.Message,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTargets = `-- name: ListTargets :many
SELECT user_id FROM reminder_targets WHERE reminder_id = $1 ORDER BY user_id
`

func (q *Queries) ListTargets(ctx context.Context, reminderID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTargets, reminderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAck = `-- name: UpsertAck :exec
INSERT INTO reminder_acks (reminder_id, user_id, acked_at) VALUES ($1, $2, $3)
ON CONFLICT(reminder_id, user_id) DO UPDATE SET acked_at = excluded.acked_at
`

type UpsertAckParams struct {
	ReminderID string `json:"reminder_id"`
	UserID     string `json:"user_id"`
	AckedAt    int64  `json:"acked_at"`
}

func (q *Queries) UpsertAck(ctx context.Context, arg UpsertAckParams) error {
	_, err := q.db.ExecContext(ctx, upsertAck, arg.ReminderID, arg.UserID, arg.AckedAt)
	return err
}

const upsertReminder = `-- name: UpsertReminder :exec
INSERT INTO reminders (id, schedule_kind, trigger_at, next_run_at, recur_every_seconds, valid_until,
    requires_ack, completion_policy, profile, status, last_fired_at, source, owner, message, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT(id) DO UPDATE SET
    schedule_kind = excluded.schedule_kind,
    trigger_at = excluded.trigger_at,
    next_run_at = excluded.next_run_at,
    recur_every_seconds = excluded.recur_every_seconds,
    valid_until = excluded.valid_until,
    requires_ack = excluded.requires_ack,
    completion_policy = excluded.completion_policy,
    profile = excluded.profile,
    status = excluded.status,
    last_fired_at = excluded.last_fired_at,
    source = excluded.source,
    owner = excluded.owner,
    message = excluded.message,
    updated_at = excluded.updated_at
`

type UpsertReminderParams struct {
	ID                string        `json:"id"`
	ScheduleKind      string        `json:"schedule_kind"`
	TriggerAt         int64         `json:"trigger_at"`
	NextRunAt         sql.NullInt64 `json:"next_run_at"`
	RecurEverySeconds sql.NullInt64 `json:"recur_every_seconds"`
	ValidUntil        sql.NullInt64 `json:"valid_until"`
	RequiresAck       int64         `json:"requires_ack"`
	CompletionPolicy  string        `json:"completion_policy"`
	Profile           string        `json:"profile"`
	Status            string        `json:"status"`
	LastFiredAt       sql.NullInt64 `json:"last_fired_at"`
	Source            string        `json:"source"`
	Owner             string        `json:"owner"`
	Message           string        `json:"message"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
}

func (q *Queries) UpsertReminder(ctx context.Context, arg UpsertReminderParams) error {
	_, err := q.db.ExecContext(ctx, upsertReminder,
		arg.ID,
		arg.ScheduleKind,
		arg.TriggerAt,
		arg.NextRunAt,
		arg.RecurEverySeconds,
		arg.ValidUntil,
		arg.RequiresAck,
		arg.CompletionPolicy,
		arg.Profile,
		arg.Status,
		arg.LastFiredAt,
		arg.Source,
		arg.Owner,
		arg.Message,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertTarget = `-- name: UpsertTarget :exec
INSERT INTO reminder_targets (reminder_id, user_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type UpsertTargetParams struct {
	ReminderID string `json:"reminder_id"`
	UserID     string `json:"user_id"`
}

func (q *Queries) UpsertTarget(ctx context.Context, arg UpsertTargetParams) error {
	_, err := q.db.ExecContext(ctx, upsertTarget, arg.ReminderID, arg.UserID)
	return err
}
