// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=mock_ha_service.go -package=mocks -source=interfaces.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
	gome_assistant "saml.dev/gome-assistant"
)

// MockHAService is a mock of HAService interface.
type MockHAService struct {
	ctrl     *gomock.Controller
	recorder *MockHAServiceMockRecorder
	isgomock struct{}
}

// MockHAServiceMockRecorder is the mock recorder for MockHAService.
type MockHAServiceMockRecorder struct {
	mock *MockHAService
}

// NewMockHAService creates a new mock instance.
func NewMockHAService(ctrl *gomock.Controller) *MockHAService {
	mock := &MockHAService{ctrl: ctrl}
	mock.recorder = &MockHAServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHAService) EXPECT() *MockHAServiceMockRecorder {
	return m.recorder
}

// MockHAState is a mock of HAState interface.
type MockHAState struct {
	ctrl     *gomock.Controller
	recorder *MockHAStateMockRecorder
	isgomock struct{}
}

// MockHAStateMockRecorder is the mock recorder for MockHAState.
type MockHAStateMockRecorder struct {
	mock *MockHAState
}

// NewMockHAState creates a new mock instance.
func NewMockHAState(ctrl *gomock.Controller) *MockHAState {
	mock := &MockHAState{ctrl: ctrl}
	mock.recorder = &MockHAStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHAState) EXPECT() *MockHAStateMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHAState) Get(entityID string) (gome_assistant.EntityState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", entityID)
	ret0, _ := ret[0].(gome_assistant.EntityState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHAStateMockRecorder) Get(entityID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHAState)(nil).Get), entityID)
}

// MockPricingService is a mock of PricingService interface.
type MockPricingService struct {
	ctrl     *gomock.Controller
	recorder *MockPricingServiceMockRecorder
	isgomock struct{}
}

// MockPricingServiceMockRecorder is the mock recorder for MockPricingService.
type MockPricingServiceMockRecorder struct {
	mock *MockPricingService
}

// NewMockPricingService creates a new mock instance.
func NewMockPricingService(ctrl *gomock.Controller) *MockPricingService {
	mock := &MockPricingService{ctrl: ctrl}
	mock.recorder = &MockPricingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingService) EXPECT() *MockPricingServiceMockRecorder {
	return m.recorder
}

// GetAveragePrice mocks base method.
func (m *MockPricingService) GetAveragePrice() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAveragePrice")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAveragePrice indicates an expected call of GetAveragePrice.
func (mr *MockPricingServiceMockRecorder) GetAveragePrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAveragePrice", reflect.TypeOf((*MockPricingService)(nil).GetAveragePrice))
}

// GetCurrentPrice mocks base method.
func (m *MockPricingService) GetCurrentPrice() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockPricingServiceMockRecorder) GetCurrentPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockPricingService)(nil).GetCurrentPrice))
}

// GetPriceSlots mocks base method.
func (m *MockPricingService) GetPriceSlots() ([]PriceSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceSlots")
	ret0, _ := ret[0].([]PriceSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceSlots indicates an expected call of GetPriceSlots.
func (mr *MockPricingServiceMockRecorder) GetPriceSlots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceSlots", reflect.TypeOf((*MockPricingService)(nil).GetPriceSlots))
}

// GetPriceSlotsInWindow mocks base method.
func (m *MockPricingService) GetPriceSlotsInWindow(from, until time.Time) ([]PriceSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPriceSlotsInWindow", from, until)
	ret0, _ := ret[0].([]PriceSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPriceSlotsInWindow indicates an expected call of GetPriceSlotsInWindow.
func (mr *MockPricingServiceMockRecorder) GetPriceSlotsInWindow(from, until any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPriceSlotsInWindow", reflect.TypeOf((*MockPricingService)(nil).GetPriceSlotsInWindow), from, until)
}

// IsCurrentlyExpensive mocks base method.
func (m *MockPricingService) IsCurrentlyExpensive() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCurrentlyExpensive")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsCurrentlyExpensive indicates an expected call of IsCurrentlyExpensive.
func (mr *MockPricingServiceMockRecorder) IsCurrentlyExpensive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCurrentlyExpensive", reflect.TypeOf((*MockPricingService)(nil).IsCurrentlyExpensive))
}
