// Code generated by MockGen. DO NOT EDIT.
// Source: home-go/internal/tech/mcp/pricing (interfaces: PricingService)
//
// Generated by this command:
//
//	mockgen -destination=../../../mocks/tech/mcp/pricing/pricing_service.go -package=pricing home-go/internal/tech/mcp/pricing PricingService
//

// Package pricing is a generated GoMock package.
package pricing

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPricingService is a mock of PricingService interface.
type MockPricingService struct {
	ctrl     *gomock.Controller
	recorder *MockPricingServiceMockRecorder
	isgomock struct{}
}

// MockPricingServiceMockRecorder is the mock recorder for MockPricingService.
type MockPricingServiceMockRecorder struct {
	mock *MockPricingService
}

// NewMockPricingService creates a new mock instance.
func NewMockPricingService(ctrl *gomock.Controller) *MockPricingService {
	mock := &MockPricingService{ctrl: ctrl}
	mock.recorder = &MockPricingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPricingService) EXPECT() *MockPricingServiceMockRecorder {
	return m.recorder
}

// GetCurrentPrice mocks base method.
func (m *MockPricingService) GetCurrentPrice() (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentPrice")
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentPrice indicates an expected call of GetCurrentPrice.
func (mr *MockPricingServiceMockRecorder) GetCurrentPrice() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentPrice", reflect.TypeOf((*MockPricingService)(nil).GetCurrentPrice))
}
