alias: "[reminder] Remind to heal the head"
description: ""
triggers:
  - trigger: time
    at: "16:00:00"
    weekday:
      - mon
      - wed
      - fri
conditions:
  - condition: state
    entity_id: input_select.house_mode
    state: At home
actions:
  - action: input_boolean.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: input_boolean.head_healed
  - action: tts.speak
    metadata: {}
    data:
      cache: false
      media_player_entity_id: media_player.living_room_google_home
      message: Chookity, don't forget about your head
    target:
      entity_id: tts.piper
  - repeat:
      until:
        - condition: or
          conditions:
            - condition: state
              entity_id: input_boolean.head_healed
              state: "on"
            - condition: not
              conditions:
                - condition: state
                  entity_id: input_select.house_mode
                  state: At home
      sequence:
        - delay:
            hours: 0
            minutes: 20
            seconds: 0
            milliseconds: 0
        - condition: state
          entity_id: input_boolean.head_healed
          state: "off"
        - action: tts.speak
          metadata: {}
          data:
            cache: true
            media_player_entity_id: media_player.living_room_google_home
            message: Reminder to heal the head
          target:
            entity_id: tts.piper
mode: single
