services:
  home-go:
    image: ghcr.io/azarakovskiy/home-go:master
    restart: unless-stopped
    env_file: .env
    volumes:
      - data:/data
    environment:
      SQLITE_PATH: /data/home_go.db

volumes:
  data:
