// Code generated by MockGen. DO NOT EDIT.
// Source: home-go/internal/domain/reminders (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=internal/domain/reminders/mocks/mock_repository.go -package=mocks home-go/internal/domain/reminders Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reminders "home-go/internal/domain/reminders"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id reminders.ReminderID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id reminders.ReminderID) (reminders.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(reminders.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// ListActive mocks base method.
func (m *MockRepository) ListActive(ctx context.Context) ([]reminders.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]reminders.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockRepositoryMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockRepository)(nil).ListActive), ctx)
}

// ListDueBefore mocks base method.
func (m *MockRepository) ListDueBefore(ctx context.Context, t time.Time) ([]reminders.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDueBefore", ctx, t)
	ret0, _ := ret[0].([]reminders.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDueBefore indicates an expected call of ListDueBefore.
func (mr *MockRepositoryMockRecorder) ListDueBefore(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDueBefore", reflect.TypeOf((*MockRepository)(nil).ListDueBefore), ctx, t)
}

// Save mocks base method.
func (m *MockRepository) Save(ctx context.Context, r reminders.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockRepositoryMockRecorder) Save(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockRepository)(nil).Save), ctx, r)
}
