- triggers:
  - trigger: time_pattern
    seconds: "/30"
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_kersenboogerd_hoofddorp_4100
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_hoofddorp_kersenboogerd_4100
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_enkhuizen_amsterdam_via_purmerend_3700
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_amsterdam_enkhuizen_via_purmerend_3700
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_enkhuizen_maastrict_2900
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_maastrict_enkhuizen_2900
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_enkhuizen_veerlen_3900
  - trigger: state
    entity_id: sensor.cached_train_nearby_time_maastrict_enkhuizen_3900
  binary_sensor:
    - name: "Train Nearby"
      icon: mdi:train
      device_class: presence
      state: >
        {{ 
            is_state('sensor.cached_train_nearby_time_kersenboogerd_hoofddorp_4100', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_hoofddorp_kersenboogerd_4100', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_enkhuizen_amsterdam_via_purmerend_3700', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_amsterdam_enkhuizen_via_purmerend_3700', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_enkhuizen_maastrict_2900', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_maastrict_enkhuizen_2900', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_enkhuizen_veerlen_3900', now().strftime('%Y-%m-%d %H:%M'))
            or is_state('sensor.cached_train_nearby_time_maastrict_enkhuizen_3900', now().strftime('%Y-%m-%d %H:%M'))
        }}